USE [master]
GO
/****** Object:  Database [DB_GSMS_Full_SWD]    Script Date: 09/05/2023 15:32:00 ******/
CREATE DATABASE [DB_GSMS_Full_SWD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_GSMS', FILENAME = N'D:\SQL\SQLServer2019\MSSQL15.MSSQLSERVER\MSSQL\DATA\DB_GSMS_SWD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB_GSMS_log', FILENAME = N'D:\SQL\SQLServer2019\MSSQL15.MSSQLSERVER\MSSQL\DATA\DB_GSMS_SWD_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_GSMS_Full_SWD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET ARITHABORT OFF 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET  DISABLE_BROKER 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET RECOVERY FULL 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET  MULTI_USER 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'DB_GSMS_Full_SWD', N'ON'
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET QUERY_STORE = OFF
GO
USE [DB_GSMS_Full_SWD]
GO
/****** Object:  Table [dbo].[Brand]    Script Date: 09/05/2023 15:32:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Brand](
	[Id] [nvarchar](40) NOT NULL,
	[Name] [nvarchar](50) NULL,
	[CreatedDate] [datetime] NULL,
	[IsDeleted] [bit] NULL,
 CONSTRAINT [PK_Brands] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Category]    Script Date: 09/05/2023 15:32:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Category](
	[Id] [nvarchar](40) NOT NULL,
	[Name] [nvarchar](50) NULL,
	[IsDeleted] [bit] NULL,
 CONSTRAINT [PK_Categories] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ImportOrder]    Script Date: 09/05/2023 15:32:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ImportOrder](
	[Id] [nvarchar](40) NOT NULL,
	[Name] [nvarchar](50) NULL,
	[ProductId] [nvarchar](40) NULL,
	[StoreId] [nvarchar](40) NULL,
	[IsDeleted] [bit] NULL,
 CONSTRAINT [PK_ImportOrders] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ImportOrderDetail]    Script Date: 09/05/2023 15:32:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ImportOrderDetail](
	[Id] [nvarchar](40) NOT NULL,
	[OrderId] [nvarchar](40) NULL,
	[Name] [nvarchar](50) NULL,
	[Distributor] [nvarchar](50) NULL,
	[ProductId] [nvarchar](40) NULL,
	[Quantity] [int] NULL,
	[IsDeleted] [bit] NULL,
	[ManufacturingDate] [datetime] NULL,
	[ExpiringDate] [datetime] NULL,
 CONSTRAINT [PK_ImportOrderDetails] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Product]    Script Date: 09/05/2023 15:32:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Product](
	[Id] [nvarchar](40) NOT NULL,
	[AtomicPrice] [money] NULL,
	[MasterProductId] [nvarchar](40) NOT NULL,
	[Name] [nvarchar](50) NULL,
	[CategoryId] [nvarchar](40) NULL,
	[IsDeleted] [bit] NULL,
 CONSTRAINT [PK_Products_1] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProductDetail]    Script Date: 09/05/2023 15:32:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProductDetail](
	[Id] [nvarchar](40) NOT NULL,
	[ProductId] [nvarchar](40) NULL,
	[Price] [money] NULL,
	[Status] [nvarchar](40) NULL,
	[StoredQuantity] [int] NULL,
	[CreatedDate] [datetime] NULL,
 CONSTRAINT [PK_ProductDetails] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Receipt]    Script Date: 09/05/2023 15:32:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Receipt](
	[Id] [nvarchar](40) NOT NULL,
	[CustomerId] [nvarchar](40) NULL,
	[EmployeeId] [nvarchar](40) NULL,
	[StoreId] [nvarchar](40) NULL,
	[CreatedDate] [datetime] NULL,
	[IsDeleted] [bit] NULL,
 CONSTRAINT [PK_Receipts] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ReceiptDetail]    Script Date: 09/05/2023 15:32:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ReceiptDetail](
	[Id] [nvarchar](40) NOT NULL,
	[ReceiptId] [nvarchar](40) NULL,
	[ProductId] [nvarchar](40) NULL,
	[Quantity] [int] NULL,
	[CreatedDate] [datetime] NULL,
 CONSTRAINT [PK_ReceiptProductDetails] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Store]    Script Date: 09/05/2023 15:32:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Store](
	[Id] [nvarchar](40) NOT NULL,
	[Name] [nvarchar](50) NULL,
	[BrandId] [nvarchar](40) NULL,
	[CreatedDate] [datetime] NULL,
	[IsDeleted] [int] NULL,
 CONSTRAINT [PK_Stores] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ImportOrder]  WITH CHECK ADD  CONSTRAINT [FK_ImportOrder_Store] FOREIGN KEY([StoreId])
REFERENCES [dbo].[Store] ([Id])
GO
ALTER TABLE [dbo].[ImportOrder] CHECK CONSTRAINT [FK_ImportOrder_Store]
GO
ALTER TABLE [dbo].[ImportOrderDetail]  WITH CHECK ADD  CONSTRAINT [FK_ImportOrderDetail_Product] FOREIGN KEY([ProductId])
REFERENCES [dbo].[Product] ([Id])
GO
ALTER TABLE [dbo].[ImportOrderDetail] CHECK CONSTRAINT [FK_ImportOrderDetail_Product]
GO
ALTER TABLE [dbo].[ImportOrderDetail]  WITH CHECK ADD  CONSTRAINT [FK_ImportOrderDetails_ImportOrders] FOREIGN KEY([OrderId])
REFERENCES [dbo].[ImportOrder] ([Id])
GO
ALTER TABLE [dbo].[ImportOrderDetail] CHECK CONSTRAINT [FK_ImportOrderDetails_ImportOrders]
GO
ALTER TABLE [dbo].[Product]  WITH CHECK ADD  CONSTRAINT [FK_Products_Categories] FOREIGN KEY([CategoryId])
REFERENCES [dbo].[Category] ([Id])
GO
ALTER TABLE [dbo].[Product] CHECK CONSTRAINT [FK_Products_Categories]
GO
ALTER TABLE [dbo].[ProductDetail]  WITH CHECK ADD  CONSTRAINT [FK_ProductDetails_Products] FOREIGN KEY([ProductId])
REFERENCES [dbo].[Product] ([Id])
GO
ALTER TABLE [dbo].[ProductDetail] CHECK CONSTRAINT [FK_ProductDetails_Products]
GO
ALTER TABLE [dbo].[Receipt]  WITH CHECK ADD  CONSTRAINT [FK_Receipts_Stores] FOREIGN KEY([StoreId])
REFERENCES [dbo].[Store] ([Id])
GO
ALTER TABLE [dbo].[Receipt] CHECK CONSTRAINT [FK_Receipts_Stores]
GO
ALTER TABLE [dbo].[ReceiptDetail]  WITH CHECK ADD  CONSTRAINT [FK_ReceiptDetail_Product] FOREIGN KEY([ProductId])
REFERENCES [dbo].[Product] ([Id])
GO
ALTER TABLE [dbo].[ReceiptDetail] CHECK CONSTRAINT [FK_ReceiptDetail_Product]
GO
ALTER TABLE [dbo].[ReceiptDetail]  WITH CHECK ADD  CONSTRAINT [FK_ReceiptDetails_Receipts] FOREIGN KEY([ReceiptId])
REFERENCES [dbo].[Receipt] ([Id])
GO
ALTER TABLE [dbo].[ReceiptDetail] CHECK CONSTRAINT [FK_ReceiptDetails_Receipts]
GO
ALTER TABLE [dbo].[Store]  WITH CHECK ADD  CONSTRAINT [FK_Stores_Brands] FOREIGN KEY([BrandId])
REFERENCES [dbo].[Brand] ([Id])
GO
ALTER TABLE [dbo].[Store] CHECK CONSTRAINT [FK_Stores_Brands]
GO
USE [master]
GO
ALTER DATABASE [DB_GSMS_Full_SWD] SET  READ_WRITE 
GO
